use keld_source::Span;

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum Keyword {
    Any,
    As,
    Break,
    Continue,
    Else,
    Entity,
    Enum,
    Extern,
    False,
    Fn,
    Handle,
    If,
    In,
    Keep,
    Let,
    Lifecycle,
    Link,
    Match,
    Module,
    None,
    Pub,
    Raises,
    Retire,
    Retires,
    Return,
    Struct,
    Take,
    True,
    Try,
    Unsafe,
    Use,
    Var,
    When,
    While,
    Async,
    Await,
    Dynamic,
    Impl,
    Interface,
    Resource,
    Shared,
}

impl Keyword {
    pub(crate) fn from_identifier(identifier: &str) -> Option<Self> {
        Some(match identifier {
            "any" => Self::Any,
            "as" => Self::As,
            "break" => Self::Break,
            "continue" => Self::Continue,
            "else" => Self::Else,
            "entity" => Self::Entity,
            "enum" => Self::Enum,
            "extern" => Self::Extern,
            "false" => Self::False,
            "fn" => Self::Fn,
            "handle" => Self::Handle,
            "if" => Self::If,
            "in" => Self::In,
            "keep" => Self::Keep,
            "let" => Self::Let,
            "lifecycle" => Self::Lifecycle,
            "link" => Self::Link,
            "match" => Self::Match,
            "module" => Self::Module,
            "none" => Self::None,
            "pub" => Self::Pub,
            "raises" => Self::Raises,
            "retire" => Self::Retire,
            "retires" => Self::Retires,
            "return" => Self::Return,
            "struct" => Self::Struct,
            "take" => Self::Take,
            "true" => Self::True,
            "try" => Self::Try,
            "unsafe" => Self::Unsafe,
            "use" => Self::Use,
            "var" => Self::Var,
            "when" => Self::When,
            "while" => Self::While,
            "async" => Self::Async,
            "await" => Self::Await,
            "dynamic" => Self::Dynamic,
            "impl" => Self::Impl,
            "interface" => Self::Interface,
            "resource" => Self::Resource,
            "shared" => Self::Shared,
            _ => return None,
        })
    }
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum Punct {
    LParen,
    RParen,
    LBrace,
    RBrace,
    LBracket,
    RBracket,
    Comma,
    Dot,
    Colon,
    Question,
    Semicolon,
    Underscore,
    Eq,
    FatArrow,
    Arrow,
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    PlusEq,
    MinusEq,
    StarEq,
    SlashEq,
    PercentEq,
    Bang,
    BangEq,
    EqEq,
    Less,
    LessEq,
    Greater,
    GreaterEq,
    Shl,
    Shr,
    AndAnd,
    OrOr,
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum TokenKind {
    Ident,
    Int,
    String,
    Keyword(Keyword),
    Punct(Punct),
    Term,
    Whitespace,
    LineComment,
    BlockComment,
    Error,
    Eof,
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub struct TokenId(pub u32);

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Token {
    pub kind: TokenKind,
    pub span: Span,
    pub synthetic: bool,
}
