[package]
name = "keld-cli"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "keld"
path = "src/main.rs"

[dependencies]
keld-flow = { path = "../keld-flow" }
keld-interpreter = { path = "../keld-interpreter" }
keld-ir = { path = "../keld-ir" }
keld-lifecycle = { path = "../keld-lifecycle" }
keld-storage = { path = "../keld-storage" }
keld-semantics = { path = "../keld-semantics" }
keld-source = { path = "../keld-source" }
keld-syntax = { path = "../keld-syntax" }

[lints]
workspace = true
