[package]
name = "keld-semantics"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
keld-numeric = { path = "../keld-numeric" }
keld-source = { path = "../keld-source" }
keld-syntax = { path = "../keld-syntax" }

[lints]
workspace = true
